version: '3.9'

services:

  postgres-dbt:
    image: postgres
    container_name: postgres-dbt
    # networks:
    #   - juans_network
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER: dbtuser
      POSTGRES_DB: dbtdb
      DBT_SCHEMA: dbt
      DBT_RAW_DATA_SCHEMA: dbt_raw_data
    expose:
      - 5432
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    # networks:
    #   - juans_network
    restart: always
    ports:
      - 8080:8080